[package]
name = "tetris_core"
version = "0.1.0"
authors = ["freestrings <freestrings@gmail.com>"]

[dependencies]
rand = "0.3"
lazy_static = "0.2"
time = "0.1"
libc = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
emscripten-sys = "0.3"
